"""empty message

Revision ID: b5be107dcaf7
Revises: 831a0030a192
Create Date: 2022-08-12 10:11:45.384377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5be107dcaf7'
down_revision = '831a0030a192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['poster_id'], ['id'])
    op.add_column('users', sa.Column('about_author', sa.Text(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_author')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    # ### end Alembic commands ###
